export const LOCATIONS: Record<string, string[]> = {
  "Mary": [
    "Mary ş.",
    "Baýramaly ş.",
    "Sakarçäge",
    "Murgap",
    "Ýolöten",
    "Türkmengala",
  ],
  "Ahal": [
    "Änew",
    "Gökdepe",
    "Baharly",
    "Ak bugdaý",
    "Arkadag ş.",
  ],
  "Balkan": [
    "Balkanabat",
    "Türkmenbaşy ş.",
    "Hazar",
    "Gumdag",
  ],
  "Lebap": [
    "Türkmenabat ş.",
    "Kerki",
    "Saýat",
    "Çärjew",
  ],
  "Daşoguz": [
    "Daşoguz ş.",
    "Köneürgenç",
    "Akdepe",
  ],
  "Aşgabat": [
    "Büzmeýin",
    "Köpetdag",
    "Bagtyýarlyk",
    "Berkararlyk",
    "Ruhabat",
  ],
};

export const JOB_CATEGORIES = [
  { id: "gurlusyk", tm: "Gurluşyk", ru: "Строительство", icon: "hammer-outline" },
  { id: "lukman", tm: "Lukman", ru: "Врач", icon: "medkit-outline" },
  { id: "programmist", tm: "Programmist", ru: "Программист", icon: "laptop-outline" },
  { id: "suruji", tm: "Sürüji", ru: "Водитель", icon: "car-outline" },
];

export const SERVICE_CATEGORIES = [
  { id: "santehnik", tm: "Santehnik", ru: "Сантехник", icon: "water-outline", color: "#0EA5E9", emoji: "🔧" },
  { id: "elektrik", tm: "Elektrik", ru: "Электрик", icon: "flash-outline", color: "#EAB308", emoji: "⚡" },
  { id: "telewizor", tm: "Telewizor ussasy", ru: "Телемастер", icon: "tv-outline", color: "#8B5CF6", emoji: "📺" },
  { id: "holodilnik", tm: "Holodilnik ussasy", ru: "Мастер холодильников", icon: "snow-outline", color: "#06B6D4", emoji: "❄️" },
];

export const EDUCATION_OPTIONS = [
  { value: "orta", tm: "Orta bilim", ru: "Среднее образование" },
  { value: "orta_hünär", tm: "Orta hünär bilimi", ru: "Среднее специальное" },
  { value: "ýokary", tm: "Ýokary bilim", ru: "Высшее образование" },
  { value: "magistr", tm: "Magistratura", ru: "Магистратура" },
  { value: "kandidat", tm: "Ylymlar kandidaty", ru: "Кандидат наук" },
];

export type Listing = {
  id: string;
  type: "job" | "service";
  categoryId: string;
  title: string;
  titleRu: string;
  description: string;
  descriptionRu: string;
  region: string;
  district: string;
  price: number;
  currency: string;
  phone: string;
  whatsapp?: string;
  telegram?: string;
  posterName: string;
  workHours?: string;
  lunchProvided?: boolean;
  transportProvided?: boolean;
  createdAt: string;
};

export const SAMPLE_LISTINGS: Listing[] = [
  {
    id: "1",
    type: "job",
    categoryId: "gurlusyk",
    title: "Gurluşyk işçisi gerek",
    titleRu: "Требуется строительный рабочий",
    description: "Ýaşaýyş jaýyny gurmak üçin tejribeli gurluşyk işçisi gerek. Iş wagty 08:00-18:00.",
    descriptionRu: "Требуется опытный строительный рабочий для строительства жилого дома.",
    region: "Mary",
    district: "Mary ş.",
    price: 1800,
    currency: "TMT",
    phone: "+99362123456",
    whatsapp: "+99362123456",
    telegram: "@merdan_builder",
    posterName: "Merdan Amanow",
    workHours: "08:00 - 18:00",
    lunchProvided: true,
    transportProvided: false,
    createdAt: "2026-03-20",
  },
  {
    id: "2",
    type: "job",
    categoryId: "lukman",
    title: "Maşgala lukmany gerek",
    titleRu: "Требуется семейный врач",
    description: "Hususy klinika üçin tejribeli maşgala lukmany gerek.",
    descriptionRu: "В частную клинику требуется опытный семейный врач.",
    region: "Aşgabat",
    district: "Köpetdag",
    price: 4500,
    currency: "TMT",
    phone: "+99361234567",
    whatsapp: "+99361234567",
    posterName: "Aýgül Rejepowa",
    workHours: "09:00 - 18:00",
    lunchProvided: true,
    transportProvided: true,
    createdAt: "2026-03-19",
  },
  {
    id: "3",
    type: "job",
    categoryId: "programmist",
    title: "Web programmer gerek",
    titleRu: "Требуется веб-программист",
    description: "IT kompaniýasy üçin tejribeli web programmer gerek. React bilmek hökmany.",
    descriptionRu: "В IT компанию требуется опытный веб-программист. Знание React обязательно.",
    region: "Aşgabat",
    district: "Berkararlyk",
    price: 6000,
    currency: "TMT",
    phone: "+99365345678",
    whatsapp: "+99365345678",
    telegram: "@kakajan_it",
    posterName: "Kakajan Muradow",
    workHours: "09:00 - 18:00",
    lunchProvided: false,
    transportProvided: false,
    createdAt: "2026-03-18",
  },
  {
    id: "4",
    type: "job",
    categoryId: "suruji",
    title: "Ýük ulag sürüjisi gerek",
    titleRu: "Требуется водитель грузовика",
    description: "Kompaniýamyz üçin tejribeli ýük ulag sürüjisi gerek.",
    descriptionRu: "В нашу компанию требуется опытный водитель грузовика.",
    region: "Balkan",
    district: "Balkanabat",
    price: 2500,
    currency: "TMT",
    phone: "+99363456789",
    whatsapp: "+99363456789",
    posterName: "Oraz Hojamow",
    workHours: "07:00 - 19:00",
    lunchProvided: true,
    transportProvided: false,
    createdAt: "2026-03-17",
  },
  {
    id: "5",
    type: "service",
    categoryId: "santehnik",
    title: "Santehnik hyzmatlary",
    titleRu: "Сантехнические услуги",
    description: "Ähli santehnik işleri: turba çalyşmak, kranlar, duş otaglary. Öýüňize barýarys.",
    descriptionRu: "Все сантехнические работы: замена труб, кранов, душевых. Выезд на дом.",
    region: "Mary",
    district: "Sakarçäge",
    price: 150,
    currency: "TMT",
    phone: "+99364567890",
    whatsapp: "+99364567890",
    telegram: "@yhlas_plumber",
    posterName: "Yhlas Aýdogdyýew",
    createdAt: "2026-03-16",
  },
  {
    id: "6",
    type: "service",
    categoryId: "elektrik",
    title: "Elektrik hyzmatlary",
    titleRu: "Электрические услуги",
    description: "Elektrik simlerini çekmek, rozetkalar, swýçlar, yşyklandyryş. Gije-gündiz!",
    descriptionRu: "Прокладка электрических проводов, розетки, выключатели, освещение. Круглосуточно!",
    region: "Lebap",
    district: "Türkmenabat ş.",
    price: 120,
    currency: "TMT",
    phone: "+99362678901",
    whatsapp: "+99362678901",
    posterName: "Serdar Orazow",
    createdAt: "2026-03-15",
  },
  {
    id: "7",
    type: "service",
    categoryId: "telewizor",
    title: "Telewizor abatlamak",
    titleRu: "Ремонт телевизоров",
    description: "Ähli marka we model telewizorlaryny abatlamak. Öýüňize barýarys. Kepillik berilýär.",
    descriptionRu: "Ремонт телевизоров всех марок и моделей. Выезд на дом. Гарантия.",
    region: "Daşoguz",
    district: "Daşoguz ş.",
    price: 80,
    currency: "TMT",
    phone: "+99361789012",
    whatsapp: "+99361789012",
    telegram: "@dowlet_tv",
    posterName: "Döwlet Gurbannazarow",
    createdAt: "2026-03-14",
  },
  {
    id: "8",
    type: "service",
    categoryId: "holodilnik",
    title: "Holodilnik abatlamak",
    titleRu: "Ремонт холодильников",
    description: "Ähli marka holodilnikleri abatlamak. Freon doldurmak, kompressor çalyşmak.",
    descriptionRu: "Ремонт холодильников всех марок. Заправка фреоном, замена компрессора.",
    region: "Ahal",
    district: "Gökdepe",
    price: 100,
    currency: "TMT",
    phone: "+99365890123",
    whatsapp: "+99365890123",
    posterName: "Babamyrat Durdyýew",
    createdAt: "2026-03-13",
  },
  {
    id: "9",
    type: "job",
    categoryId: "gurlusyk",
    title: "Öý abatlaýjy gerek",
    titleRu: "Требуется домашний мастер",
    description: "Içki gurluşyk işleri üçin tejribeli usta gerek. Gips, boýag, remont.",
    descriptionRu: "Требуется опытный мастер для внутренних строительных работ.",
    region: "Ahal",
    district: "Änew",
    price: 2200,
    currency: "TMT",
    phone: "+99363901234",
    whatsapp: "+99363901234",
    posterName: "Gülnar Saparowa",
    workHours: "08:00 - 17:00",
    lunchProvided: false,
    transportProvided: true,
    createdAt: "2026-03-12",
  },
  {
    id: "10",
    type: "service",
    categoryId: "santehnik",
    title: "Suw ulgamy oturtmak",
    titleRu: "Установка водопровода",
    description: "Täze binalara suw ulgamy oturtmak we abatlamak hyzmatlary.",
    descriptionRu: "Услуги по установке и ремонту водопровода в новых зданиях.",
    region: "Balkan",
    district: "Türkmenbaşy ş.",
    price: 200,
    currency: "TMT",
    phone: "+99364012345",
    whatsapp: "+99364012345",
    posterName: "Amanmyrat Ataýew",
    createdAt: "2026-03-11",
  },
];
